export type PlateOrder = 'Entrante' | 'Segundo'
export type Day = 'Lunes' | 'Martes' | 'Miércoles' | 'Jueves' | 'Viernes' | 'Sábado' | 'Domingo'
export type ShopStatus = 'Abierto' | 'Cerrado'
export type BlobPaths = 'plates/'
export type MenuStatus = 'Disponible' | 'Agotado'
